[workspace]
members = [
  "hf-core",
  "hf-daemon",
  "hf-gtk",
  "hf-protocol",
  "hf-error",
  "hf-gpu",
]
resolver = "2"

[profile.release]
codegen-units = 16
lto = true
opt-level = "z"
strip = true
